pipeline:
  prepare:
    image: plugins/git
    commands:
      - git clone -b develop https://github.com/mesalock-linux/packages.git ../packages
  build-mkpkg:
    image: mesalocklinux/build-mesalock-linux
    commands:
      - ./mkpkg
  build-mesalockiso:
    image: mesalocklinux/build-mesalock-linux
    commands:
      - ./mesalockiso
  build-mesalockrootfs:
    image: mesalocklinux/build-mesalock-linux
    commands:
      - ./mesalockrootfs
  notify:
    image: drillster/drone-email
    secrets: [ plugin_host, plugin_username, plugin_password, plugin_from ]
    when:
      status: [ success, changed, failure ]
