pipeline:
  prepare:
    image: plugins/git
    commands:
      - git clone -b develop https://github.com/mesalock-linux/packages.git ../packages
  build-packages:
    image: mesalocklinux/build-mesalock-linux
    commands:
      - ./mkpkg
  build-iso:
    image: mesalocklinux/build-mesalock-linux
    commands:
      - ./mesalockiso
  build-rootfs:
    image: mesalocklinux/build-mesalock-linux
    commands:
      - ./mesalockrootfs
      - cp build/rootfs.tar.xz mesalockrootfs-dockerfile/
  build-docker-image:
    image: plugins/docker
    repo: mesalocklinux/mesalock-linux
    dockerfile: mesalockrootfs-dockerfile/Dockerfile
    context: mesalockrootfs-dockerfile
    secrets: [ docker_username, docker_password ]
    tags: [ develop ]
    when:
      branch: develop
      event: push
  notify:
    image: drillster/drone-email
    secrets: [ plugin_host, plugin_username, plugin_password, plugin_from ]
    when:
      status: [ success, changed, failure ]
